FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim
WORKDIR /app

# Install Python deps
COPY pyproject.toml uv.lock ./
ENV UV_PROJECT_ENVIRONMENT="/usr/local/" UV_LINK_MODE=copy

RUN uv sync --frozen --no-dev

# Copy the *entire* project (now includes real PNGs)
COPY . .

EXPOSE 8080

CMD ["streamlit","run","streamlit_app.py","--server.port=$PORT","--server.address=0.0.0.0"]
